/****** Object:  Table [dbo].[EmployeeContact]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EmployeeContact](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[employeeid] [int] NOT NULL,
	[homeline1] [varchar](255) NULL,
	[homeline2] [varchar](255) NULL,
	[homeline3] [varchar](255) NULL,
	[homecity] [varchar](255) NULL,
	[homestate] [varchar](255) NULL,
	[homepostcode] [varchar](50) NULL,
	[homecountry] [varchar](255) NULL,
	[homephone] [varchar](50) NULL,
	[homemobile] [varchar](50) NULL,
	[homeemail] [varchar](255) NULL,
	[workline1] [varchar](255) NULL,
	[workline2] [varchar](255) NULL,
	[workline3] [varchar](255) NULL,
	[workcity] [varchar](255) NULL,
	[workstate] [varchar](255) NULL,
	[workpostcode] [varchar](50) NULL,
	[workcountry] [varchar](255) NULL,
	[workphone] [varchar](50) NULL,
	[workextension] [varchar](50) NULL,
	[workfax] [varchar](50) NULL,
	[workmobile] [varchar](50) NULL,
	[workpager] [varchar](50) NULL,
	[workemail] [varchar](255) NULL,
	[workwebpage] [varchar](1000) NULL,
	[iFlag] [int] NULL,
	[linkedIn] [varchar](100) NULL,
	[twitter] [varchar](100) NULL,
	[skype] [varchar](100) NULL,
	[facebook] [varchar](100) NULL,
	[homepostalline1] [varchar](255) NULL,
	[homepostalline2] [varchar](255) NULL,
	[homepostalline3] [varchar](255) NULL,
	[homepostalcity] [varchar](255) NULL,
	[homepostalstate] [varchar](255) NULL,
	[homepostalpostcode] [varchar](50) NULL,
	[homepostalcountry] [varchar](255) NULL,
	[nokprimaryname] [varchar](255) NULL,
	[nokprimaryrelationship] [varchar](50) NULL,
	[nokprimaryline1] [varchar](255) NULL,
	[nokprimaryline2] [varchar](255) NULL,
	[nokprimaryline3] [varchar](255) NULL,
	[nokprimarycity] [varchar](255) NULL,
	[nokprimarystate] [varchar](255) NULL,
	[nokprimarypostcode] [varchar](50) NULL,
	[nokprimarycountry] [varchar](255) NULL,
	[nokprimaryphone] [varchar](50) NULL,
	[nokprimaryextension] [varchar](50) NULL,
	[nokprimarymobile] [varchar](50) NULL,
	[nokprimaryemail] [varchar](255) NULL,
	[workpostalline1] [varchar](255) NULL,
	[workpostalline2] [varchar](255) NULL,
	[workpostalline3] [varchar](255) NULL,
	[workpostalcity] [varchar](255) NULL,
	[workpostalstate] [varchar](255) NULL,
	[workpostalpostcode] [varchar](50) NULL,
	[workpostalcountry] [varchar](255) NULL,
	[noksecondaryline1] [varchar](255) NULL,
	[noksecondaryline2] [varchar](255) NULL,
	[noksecondaryline3] [varchar](255) NULL,
	[noksecondarycity] [varchar](255) NULL,
	[noksecondarystate] [varchar](255) NULL,
	[noksecondarypostcode] [varchar](50) NULL,
	[noksecondarycountry] [varchar](255) NULL,
	[noksecondaryphone] [varchar](50) NULL,
	[noksecondaryextension] [varchar](50) NULL,
	[noksecondarymobile] [varchar](50) NULL,
	[noksecondaryemail] [varchar](255) NULL,
	[noksecondaryname] [varchar](255) NULL,
	[noksecondaryrelationship] [varchar](255) NULL,
	[DrName1] [varchar](50) NULL,
	[DrContactNumber1] [varchar](50) NULL,
	[DrComment1] [varchar](255) NULL,
	[DrName2] [varchar](50) NULL,
	[DrContactNumber2] [varchar](50) NULL,
	[DrComment2] [varchar](255) NULL,
 CONSTRAINT [PK_EmployeeContact] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EmployeeContact]  WITH CHECK ADD  CONSTRAINT [FK_EmployeeContact_Employee] FOREIGN KEY([employeeid])
REFERENCES [dbo].[Employee] ([id])
ALTER TABLE [dbo].[EmployeeContact] CHECK CONSTRAINT [FK_EmployeeContact_Employee]
