/****** Object:  Table [dbo].[Employee]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Employee](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[firstname] [varchar](50) NULL,
	[secondname] [varchar](50) NULL,
	[thirdname] [varchar](50) NULL,
	[surname] [varchar](50) NULL,
	[displayname] [varchar](50) NULL,
	[firstnamepreferred] [varchar](50) NULL,
	[title] [varchar](50) NULL,
	[picture] [varchar](1000) NULL,
	[accountname] [varchar](255) NULL,
	[status] [varchar](50) NULL,
	[type] [varchar](50) NULL,
	[dob] [datetime] NULL,
	[commencement] [datetime] NULL,
	[termination] [datetime] NULL,
	[suspended] [datetime] NULL,
	[gender] [varchar](50) NULL,
	[maritalstatus] [varchar](50) NULL,
	[ethnicity] [varchar](50) NULL,
	[nationality] [varchar](50) NULL,
	[location] [varchar](50) NULL,
	[age] [tinyint] NULL,
	[companyserviceyears] [decimal](18, 8) NULL,
	[availabilitystatusid] [int] NOT NULL,
	[availabilitymessage] [varchar](1000) NULL,
	[identifier] [varchar](255) NOT NULL,
	[iFlag] [int] NULL,
	[empdate1] [datetime] NULL,
	[empdate2] [datetime] NULL,
	[empdate3] [datetime] NULL,
	[empdate4] [datetime] NULL,
	[empdate5] [datetime] NULL,
	[empdate6] [datetime] NULL,
	[empdate7] [datetime] NULL,
	[empdate8] [datetime] NULL,
	[empdate9] [datetime] NULL,
	[empdate10] [datetime] NULL,
	[empinteger1] [int] NULL,
	[empinteger2] [int] NULL,
	[empinteger3] [int] NULL,
	[empinteger4] [int] NULL,
	[empinteger5] [int] NULL,
	[empinteger6] [int] NULL,
	[empinteger7] [int] NULL,
	[empinteger8] [int] NULL,
	[empinteger9] [int] NULL,
	[empinteger10] [int] NULL,
	[empdecimal1] [decimal](18, 8) NULL,
	[empdecimal2] [decimal](18, 8) NULL,
	[empdecimal3] [decimal](18, 8) NULL,
	[empdecimal4] [decimal](18, 8) NULL,
	[empdecimal5] [decimal](18, 8) NULL,
	[empdecimal6] [decimal](18, 8) NULL,
	[empdecimal7] [decimal](18, 8) NULL,
	[empdecimal8] [decimal](18, 8) NULL,
	[empdecimal9] [decimal](18, 8) NULL,
	[empdecimal10] [decimal](18, 8) NULL,
	[emptext1] [varchar](255) NULL,
	[emptext2] [varchar](255) NULL,
	[emptext3] [varchar](255) NULL,
	[emptext4] [varchar](255) NULL,
	[emptext5] [varchar](255) NULL,
	[emptext6] [varchar](255) NULL,
	[emptext7] [varchar](255) NULL,
	[emptext8] [varchar](255) NULL,
	[emptext9] [varchar](255) NULL,
	[emptext10] [varchar](255) NULL,
	[empurl1] [varchar](1000) NULL,
	[empurl2] [varchar](1000) NULL,
	[empurl3] [varchar](1000) NULL,
	[empurl4] [varchar](1000) NULL,
	[empurl5] [varchar](1000) NULL,
	[empurl6] [varchar](1000) NULL,
	[empurl7] [varchar](1000) NULL,
	[empurl8] [varchar](1000) NULL,
	[empurl9] [varchar](1000) NULL,
	[empurl10] [varchar](1000) NULL,
	[primaryskills] [varchar](1000) NULL,
	[secondaryskills] [varchar](1000) NULL,
	[education] [varchar](255) NULL,
	[medicalalert] [varchar](1000) NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreateUserAccount] [bit] NOT NULL,
	[UpdatedAvailabilityMessageDateTime] [datetime] NULL,
	[annualleavedue] [decimal](18, 8) NULL,
	[lsldue] [decimal](18, 8) NULL,
	[basesalary] [decimal](18, 8) NULL,
	[empinteger11] [int] NULL,
	[empinteger12] [int] NULL,
	[empinteger13] [int] NULL,
	[empinteger14] [int] NULL,
	[empinteger15] [int] NULL,
	[empinteger16] [int] NULL,
	[empinteger17] [int] NULL,
	[empinteger18] [int] NULL,
	[empinteger19] [int] NULL,
	[empinteger20] [int] NULL,
	[empdecimal11] [decimal](18, 8) NULL,
	[empdecimal12] [decimal](18, 8) NULL,
	[empdecimal13] [decimal](18, 8) NULL,
	[empdecimal14] [decimal](18, 8) NULL,
	[empdecimal15] [decimal](18, 8) NULL,
	[empdecimal16] [decimal](18, 8) NULL,
	[empdecimal17] [decimal](18, 8) NULL,
	[empdecimal18] [decimal](18, 8) NULL,
	[empdecimal19] [decimal](18, 8) NULL,
	[empdecimal20] [decimal](18, 8) NULL,
	[empdecimal21] [decimal](18, 8) NULL,
	[empdecimal22] [decimal](18, 8) NULL,
	[empdecimal23] [decimal](18, 8) NULL,
	[empdecimal24] [decimal](18, 8) NULL,
	[empdecimal25] [decimal](18, 8) NULL,
	[empdecimal26] [decimal](18, 8) NULL,
	[empdecimal27] [decimal](18, 8) NULL,
	[empdecimal28] [decimal](18, 8) NULL,
	[empdecimal29] [decimal](18, 8) NULL,
	[empdecimal30] [decimal](18, 8) NULL,
	[emptext11] [varchar](255) NULL,
	[emptext12] [varchar](255) NULL,
	[emptext13] [varchar](255) NULL,
	[emptext14] [varchar](255) NULL,
	[emptext15] [varchar](255) NULL,
	[emptext16] [varchar](255) NULL,
	[emptext17] [varchar](255) NULL,
	[emptext18] [varchar](255) NULL,
	[emptext19] [varchar](255) NULL,
	[emptext20] [varchar](255) NULL,
	[emptext21] [varchar](255) NULL,
	[emptext22] [varchar](255) NULL,
	[emptext23] [varchar](255) NULL,
	[emptext24] [varchar](255) NULL,
	[emptext25] [varchar](255) NULL,
	[emptext26] [varchar](255) NULL,
	[emptext27] [varchar](255) NULL,
	[emptext28] [varchar](255) NULL,
	[emptext29] [varchar](255) NULL,
	[emptext30] [varchar](255) NULL,
	[empdate11] [datetime] NULL,
	[empdate12] [datetime] NULL,
	[empdate13] [datetime] NULL,
	[empdate14] [datetime] NULL,
	[empdate15] [datetime] NULL,
	[empdate16] [datetime] NULL,
	[empdate17] [datetime] NULL,
	[empdate18] [datetime] NULL,
	[empdate19] [datetime] NULL,
	[empdate20] [datetime] NULL,
	[empurl11] [varchar](1000) NULL,
	[empurl12] [varchar](1000) NULL,
	[empurl13] [varchar](1000) NULL,
	[empurl14] [varchar](1000) NULL,
	[empurl15] [varchar](1000) NULL,
	[empurl16] [varchar](1000) NULL,
	[empurl17] [varchar](1000) NULL,
	[empurl18] [varchar](1000) NULL,
	[empurl19] [varchar](1000) NULL,
	[empurl20] [varchar](1000) NULL,
	[basesuper] [decimal](18, 8) NULL,
	[remunerationpackage] [decimal](18, 8) NULL,
	[annualleavetaken] [decimal](18, 8) NULL,
	[sickleavetaken] [decimal](18, 8) NULL,
	[BankName1] [varchar](50) NULL,
	[BankAccntName1] [varchar](50) NULL,
	[BankBSB1] [varchar](50) NULL,
	[BankAccntNumber1] [varchar](50) NULL,
	[BankSwift1] [varchar](50) NULL,
	[BankName2] [varchar](50) NULL,
	[BankAccntName2] [varchar](50) NULL,
	[BankBSB2] [varchar](50) NULL,
	[BankAccntNumber2] [varchar](50) NULL,
	[BankSwift2] [varchar](50) NULL,
	[SuperFundCompany1] [varchar](50) NULL,
	[SuperFundProductName1] [varchar](50) NULL,
	[SuperFundABN1] [varchar](50) NULL,
	[SuperFundSPIN1] [varchar](50) NULL,
	[SuperFundAccntNumber1] [varchar](50) NULL,
	[SuperFundAccntName1] [varchar](50) NULL,
	[SuperFundCntctPerson1] [varchar](50) NULL,
	[SuperFundCntctNumber1] [varchar](50) NULL,
	[SuperFundCompany2] [varchar](50) NULL,
	[SuperFundProductName2] [varchar](50) NULL,
	[SuperFundABN2] [varchar](50) NULL,
	[SuperFundSPIN2] [varchar](50) NULL,
	[SuperFundAccntNumber2] [varchar](50) NULL,
	[SuperFundAccntName2] [varchar](50) NULL,
	[SuperFundCntctPerson2] [varchar](50) NULL,
	[SuperFundCntctNumber2] [varchar](50) NULL,
	[OnProbation] [varchar](50) NULL,
	[ProbationStartDate] [datetime] NULL,
	[ProbationEndDate] [datetime] NULL,
	[ProbationExtndEndDate] [datetime] NULL,
	[DrivingLicense] [varchar](50) NULL,
	[TaxFileNumber] [varchar](50) NULL,
	[CurrentSuperRate] [decimal](18, 8) NULL,
	[CurrentSalaryExtra1] [decimal](18, 8) NULL,
	[CurrentSalaryExtra2] [decimal](18, 8) NULL,
	[CurrentSalaryExtra3] [decimal](18, 8) NULL,
	[CurrentSalaryExtra4] [decimal](18, 8) NULL,
	[CurrentSalaryExtra5] [decimal](18, 8) NULL,
	[CurrentSalaryBaseHours] [decimal](18, 8) NULL,
	[CurrentSalaryBaseRate] [decimal](18, 8) NULL,
	[CurrentSalaryWage] [varchar](50) NULL,
	[LastSalaryUpdateDate] [datetime] NULL,
	[LastPerfReviewDate] [datetime] NULL,
	[NextSalaryReviewDate] [datetime] NULL,
	[NextPerfReviewDate] [datetime] NULL,
	[AnnualLeaveTakenTotal] [decimal](18, 8) NULL,
	[AnnualLeaveTakenThis] [decimal](18, 8) NULL,
	[AnnualLeaveRequested] [decimal](18, 8) NULL,
	[AnnualLeaveAuthorised] [decimal](18, 8) NULL,
	[AnnualLeaveNextFromDate] [datetime] NULL,
	[AnnualLeaveNextToDate] [datetime] NULL,
	[LSLTakenTotal] [decimal](18, 8) NULL,
	[LSLTakenThis] [decimal](18, 8) NULL,
	[LSLRequested] [decimal](18, 8) NULL,
	[LSLAuthorised] [decimal](18, 8) NULL,
	[SickLeaveTakenTotal] [decimal](18, 8) NULL,
	[SickLeaveTakenThis] [decimal](18, 8) NULL,
	[AbsenteeismTakenTotal] [decimal](18, 8) NULL,
	[AbsenteeismTakenThis] [decimal](18, 8) NULL,
	[UnpaidLeaveTakenTotal] [decimal](18, 8) NULL,
	[UnpaidLeaveTakenThis] [decimal](18, 8) NULL,
	[UnpaidLeaveRequested] [decimal](18, 8) NULL,
	[UnpaidLeaveAuthorised] [decimal](18, 8) NULL,
	[OtherPaidLeaveTakenTotal] [decimal](18, 8) NULL,
	[OtherPaidLeaveTakenThis] [decimal](18, 8) NULL,
	[IsCitizen] [varchar](50) NULL,
	[IsResident] [varchar](50) NULL,
	[WorkVisa] [varchar](255) NULL,
	[TerminationReason] [varchar](255) NULL,
	[PersonToWatch] [varchar](50) NULL,
	[HomeCostCentre] [varchar](50) NULL,
	[RegrettableLoss] [varchar](50) NULL,
	[SuperFundBankBSB1] [varchar](50) NULL,
	[SuperFundBankAccntNo1] [varchar](50) NULL,
	[SuperFundBankAccntName1] [varchar](50) NULL,
	[SuperFundBankBSB2] [varchar](50) NULL,
	[SuperFundBankAccntNo2] [varchar](50) NULL,
	[SuperFundBankAccntName2] [varchar](50) NULL,
	[originalcommencement] [datetime] NULL,
	[IsPlaceholder] [bit] NOT NULL,
	[HoursPerWeek] [int] NULL,
	[HourlyRate] [decimal](18, 8) NULL,
	[HolidayRegionID] [int] NULL,
	[PayrollID] [nvarchar](10) NULL,
	[AcctsPayableCode] [varchar](10) NULL,
 CONSTRAINT [pkEmployee] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [idxEmployeeIdentifier] ON [dbo].[Employee]
(
	[identifier] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [picture_Constr]  DEFAULT ('no_pic.gif') FOR [picture]
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [DF__Employee__availa__4D94879B]  DEFAULT ((1)) FOR [availabilitystatusid]
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [DF_Employee_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [DF_Employee_CreateUserAccount]  DEFAULT ((0)) FOR [CreateUserAccount]
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [DF_Employee_IsPlaceholder_1]  DEFAULT ((0)) FOR [IsPlaceholder]
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_AvailabilityStatus1] FOREIGN KEY([availabilitystatusid])
REFERENCES [dbo].[AvailabilityStatus] ([id])
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_AvailabilityStatus1]
ALTER TABLE [dbo].[Employee]  WITH NOCHECK ADD  CONSTRAINT [FK_Employee_HolidayRegion] FOREIGN KEY([HolidayRegionID])
REFERENCES [dbo].[HolidayRegion] ([ID])
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_HolidayRegion]
